### ISSUE TITLE
Traceback en nuestro entorno

### ISSUE THREAD

**Issue by anajuaristi** [avanzosc/odoo-addons#15]
Al entrar en el menú configuración de etapas de Reclamaciones da un traceback
```` 
Odoo Server Error
Traceback (most recent call last):
  File "/var/odoo/v8/OCB/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/odoo/v8/OCB/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/var/odoo/v8/OCB/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/var/odoo/v8/OCB/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/var/odoo/v8/OCB/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/OCB/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/v8/OCB/addons/web/controllers/main.py", line 905, in do_search_read
    request.context)
  File "/var/odoo/v8/OCB/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/var/odoo/v8/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/models.py", line 5129, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/var/odoo/v8/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/models.py", line 1642, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/var/odoo/v8/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/models.py", line 4638, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/var/odoo/v8/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/models.py", line 4461, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/var/odoo/v8/OCB/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/var/odoo/v8/OCB/openerp/osv/expression.py", line 812, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'type' in leaf "<osv.ExtendedLeaf: ('type', '=', 'claim') on crm_claim_stage (ctx: )>"
'''' 

Al ir a actualizar el módulo claim, para que se recarguen las vistas, da este error:
```` 
Odoo Server Error
Traceback (most recent call last):
  File "/var/odoo/v8/OCB/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/odoo/v8/OCB/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/var/odoo/v8/OCB/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/var/odoo/v8/OCB/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/var/odoo/v8/OCB/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/OCB/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/v8/OCB/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/models.py", line 3139, in read
    result = BaseModel.read(records, fields, load=load)
  File "/var/odoo/v8/OCB/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/var/odoo/v8/OCB/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/odoo/v8/OCB/openerp/models.py", line 3352, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/var/odoo/v8/OCB/openerp/osv/fields.py", line 1466, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/v8/OCB/openerp/addons/base/module/module.py", line 186, in _get_desc
    output = publish_string(source=module.description or '', settings_overrides=overrides, writer=MyWriter())
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2709, in underline
    nodes.literal_block(blocktext, blocktext), line=lineno)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 220, in warning
    return self.system_message(self.WARNING_LEVEL, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 191, in system_message
    self.stream.write(msg.astext() + '\n')
  File "/usr/lib/python2.7/dist-packages/docutils/utils/error_reporting.py", line 189, in write
    self.stream.write(data)
IOError: [Errno 5] Input/output error

````

**Comment by pedrobaeza** [comment]
Solucionado. Esto no deberías publicarlo aquí, ya que es el tracker público para los addons del repositorio.
